### ISSUE TITLE
Excluding supporting endpoints from api docs

### ISSUE THREAD

**Issue by cfuerst** [pepperize/cdk-apigateway-swagger-ui#90]
Hi, 

First of all, thank you verry much for this, very convenient and useful! 

- i for myself do not have the need to see the supporting endpoints themself inside the docs

Before any work goes into this, what's your opinion on either excluding them in the function export lambda per default or via option?

**Comment by pflorek** [comment]
Hey @cfuerst ,

yes, it's very uncommon to have API docs and swagger-ui. I really miss the GET swagger-ui css endpoints 🤣 

I was little bit lazy to either look for either an API Gateway extension or to filter the API docs.

Which solution do you prefer `disable by default` ?

**Comment by cfuerst** [comment]
Thanks for the feedback!

My opinion, no need to invest work in making this configurable etc. 
- If so, then rather injecting a custom callback function (or simmilar) somehow all the way through to the exporter to manipulate the received data from api gw export at your will (that might be handy)
- I would actually remove the functionality over disable by default, since both in theory present a BC (could only be avoided by enable by default configure to disable)
- as a plus, #92 could then be closed since there is just no need to make its schema compliant

What's your thoughts here? Cheers

**Comment by pflorek** [comment]
Hey @cfuerst ,

you're right absolutely no need. Just disable from showing up in the docs.

Yeah, or to modify the zip after it's bundled and uploaded like for edge-lambda 🤣 Just disable it 👍

**Comment by pflorek** [comment]
@cfuerst 🚀 thank you!

I think this is also resolved with https://github.com/pepperize/cdk-apigateway-swagger-ui/pull/127
