### ISSUE TITLE
basePath double slash issue

### ISSUE THREAD

**Issue by cfuerst** [pepperize/cdk-apigateway-swagger-ui#91]
I know that the actual issue comes from aws api gw export functionality, which renders server url with `url/{basePath}` and the variables again with a `/xyz`.

Event though not caused by any of this code here, would you accept a PR which is patching this in apidoc.json lambda?

Cheers

**Comment by pflorek** [comment]
Hey @cfuerst ,

yes, a PR is highly welcome 🚀

**Comment by cfuerst** [comment]
Awesome, thanks! 

Ill hand in a pr, going trough all server urls and variables, removing the  starting ` / ` at the variable on concatenation ` // ` match. Pretty sure this should not break anything for anyone.

**Comment by pflorek** [comment]
@cfuerst 🚀 thank you!

I think this is also resolved with https://github.com/pepperize/cdk-apigateway-swagger-ui/pull/127
