### ISSUE TITLE
Schema compatibility of added resources

### ISSUE THREAD

**Issue by cfuerst** [pepperize/cdk-apigateway-swagger-ui#92]
The resources and methods added do not include a response definition, which is not valid for the openapi schema validator.
In addition the route /proxy+ has issues with the parameter definition of required proxy (which do not match because of missing +)

Depending on: https://github.com/pepperize/cdk-apigateway-swagger-ui/issues/90 this should maybe be fixed? What you think?

Cheers

**Comment by pflorek** [comment]
Hey @cfuerst , I see it like you, there is no need for us to have the swagger-ui in the API docs. Apologize my laziness 😇
